End-of-rgsoc-Blogpost
rails-girls-summer-of-code/summer-of-code pull request #296
Opened 2016-09-20 15:03 UTC by theaamanda

To be published september 21st!

2016-09-20 19:40 UTC, alicetragedy commented on blog/_posts/2016-09-21-Buffering.md
> +twitter: @loadtocode
please remove the `@` symbol, as it breaks Jekyll and keeps it from building properly.

2016-09-20 19:42 UTC, alicetragedy commented on blog/_posts/2016-09-21-Buffering.md
> +![LoadtoCode KANBAN](/img/blog/2016/2016-09-21-KANBAN.gif) <font color="grey"><small><i>READY, STEADY, PUSH, DONE: Our KANBAN-Board in movement!</i></small></font><br>
add image credits to all of your images, as explained [here](https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/CONTRIBUTING.md#images).

2016-09-20 19:44 UTC, alicetragedy commented on blog/_posts/2016-09-21-Buffering.md
> +created_at: 2016-09-21
please change the format here to `Wed Sep 21 2016`

2016-09-20 19:45 UTC, alicetragedy commented on blog/_posts/2016-09-21-Buffering.md
> +permalink: blog/2016-09-19-Buffering
the permalink should have the correct date, so `blog/2016-09-21-buffering`

2016-09-20 19:46 UTC, alicetragedy requested changes
Hey @theaamanda, great post! I've made a few comments on things that need to be changed before we can publish your blog post. Please ping me if you have any questions!

2016-09-20 21:51 UTC, theaamanda commented
@alicetragedy Hey Laura, please check if its okay like this now!

2016-09-21 09:31 UTC, alicetragedy approved these changes
perfect, this is good to go now. Thanks!

2016-09-21 09:31 UTC, merged