Add Team JaM's 2nd blog post
rails-girls-summer-of-code/summer-of-code pull request #303
Opened 2016-09-27 06:35 UTC by malisas

@jeenalee and I wrote the second blog post for our team. We are scheduled for the 2016-09-28 publish date.

2016-09-27 08:01 UTC, alicetragedy requested changes
Hey @malisas great post 👍 there are just tiny changes to be made but after that's done it's ready to be merged. thanks for submitting on time!

2016-09-27 08:01 UTC, alicetragedy commented on blog/_posts/2016-09-28-almost-done-jammin.md
> +permalink: blog/2016-09-28-goodbye-jam
could you make the permalink consistent with the file name? (meaning: using the same name for both)

2016-09-27 08:01 UTC, alicetragedy commented on blog/_posts/2016-09-28-almost-done-jammin.md
> +created_at: Mon Sep 25 2016
can you make the created_at date the publishing date (same date as in the filename and permalink).

2016-09-27 08:19 UTC, malisas commented
Ok, I made the changes and squashed! Hope it's good to go :)

2016-09-28 10:07 UTC, alicetragedy approved these changes
thanks for the changes — it's all good to go!

2016-09-28 10:08 UTC, merged