B'More Stunners: Over and Out
rails-girls-summer-of-code/summer-of-code pull request #322
Opened 2016-10-18 14:09 UTC by a-jean

B'More Stunner's last blog post!

2016-10-19 21:15 UTC, alicetragedy requested changes
Good and concise post, but it's still missing a couple of things (I've made comments accordingly). The most important thing would be to add a paragraph or two about the conference itself, since there is nothing in the post about it. Please let me know if you have any questions!

2016-10-19 21:15 UTC, alicetragedy commented on blog/_posts/2016-10-16-B-More-Stunners-Over-and-Out.md
> +title: B'More Stunners&#58; B'More Stunners&#58 Over and Out!
Could you remove your team name from the title once? It's in here twice.

2016-10-19 21:15 UTC, alicetragedy commented on blog/_posts/2016-10-16-B-More-Stunners-Over-and-Out.md
> +![teamphoto](/img/blog/2016/ashley.jpeg)
All images need image credits, as clearly explained [here](https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/CONTRIBUTING.md#images). It's enough to put down your team name if you took the picture — the name of the person who took the photo is ok too.

2016-10-19 21:15 UTC, alicetragedy commented on blog/_posts/2016-10-16-B-More-Stunners-Over-and-Out.md
> +![Dance](/img/blog/2016/dino.gif)
please add an image credit to this (e.g. source of the gif if you found it on the internet)

2016-10-26 00:56 UTC, a-jean commented
Hi @alicetragedy !
I've made the changes you've requested. Let me know if there is anything else that needs to be fixed.

Thanks!

2016-10-30 08:01 UTC, merged