Team Echo: Our RGSoC Landing
rails-girls-summer-of-code/summer-of-code pull request #324
Opened 2016-10-20 18:51 UTC by nanjekyejoannah

I have just added a second blog for team Echo for publish on 21-10-2016.

2016-10-21 07:37 UTC, alicetragedy requested changes
There are a few things to fix with the date, permalink and image credits. Furthermore, all images need to have some way in which they can obviously be linked back to your article (e.g. maybe add your team name or post title as a prefix), and the `rg` images you added are very very big, so please use a compressing service to make them smaller (some examples for services can be found [here](https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/CONTRIBUTING.md#images)). After those changes are made, we can merge and publish the post. Ping me at any time if you have any questions. Thanks!

2016-10-21 07:37 UTC, alicetragedy commented on blog/_posts/2016-10-21-Team-Echo-wrapping-up.md
> +created_at: Thu July 28 2016
please change the date to the publishing one so that it's consistent with the date in the filename

2016-10-21 07:37 UTC, alicetragedy commented on blog/_posts/2016-10-21-Team-Echo-wrapping-up.md
> +permalink: blog/Team-Echo-wrapping-up-2016
the permalink needs to have the date of the post in it, as explained [here](https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/CONTRIBUTING.md#permalink).

2016-10-21 07:37 UTC, alicetragedy commented on blog/_posts/2016-10-21-Team-Echo-wrapping-up.md
> +![team picture](/img/blog/2016/team_echo2.jpg)
all images need image credits (who took the picture? Where is the image from?), you can find more about this [here](https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/CONTRIBUTING.md#images).

2016-10-21 14:59 UTC, nanjekyejoannah commented
I have compressed the rg images and that is the smallest I could have. Wondering if those are fine.If not then we might have to just do without them if it will affect.

2016-10-23 15:49 UTC, alicetragedy commented
@nanjekyejoannah that's much better, thank you! Could undo the last commit you did (renaming `img/blog/2016/TeamEcho_bg2_pyconza1.jpg` to `img/blog/2016/pyconza1.jpg`)? We want to keep the `TeamEcho_bg2_pyconza1.jpg` as a name of that file so that it shows in your post. After that we can merge and publish!

2016-10-24 08:26 UTC, alicetragedy approved these changes

2016-10-26 09:40 UTC, merged