Conference blogpost GOTOber with contributions from Team Twitches & Team Ruby's Secret
rails-girls-summer-of-code/summer-of-code pull request #339
Opened 2016-11-28 16:03 UTC by lilaluca

2016-11-28 16:29 UTC, alicetragedy requested changes
I've reviewed the post and it's almost ready to go, but the images still need to be compressed (they are much too big) and have accompanying photo credits. After these changes are made, we could probably merge!

2016-11-28 16:29 UTC, alicetragedy commented on blog/_posts/2016-11-29-intercontinental-gotober.md
> +![Nada shared her thoughts on the talk in a tweet](/img/blog/2016/20161128-GOTOber_5.jpg)<font color="grey">
this image is missing a caption and image source/credits.

2016-11-28 16:29 UTC, alicetragedy commented on blog/_posts/2016-11-29-intercontinental-gotober.md
> +So GOTO Berlin meant two days of conference in Berlin on November 14th & 15th, and it is all about learning, networking and meeting developers. But it was not just another conference. Not only Team L
maybe you could add links to all three teams' twitter accounts here in this paragraph, since you name all three? Would be awesome :)

2016-11-28 16:29 UTC, alicetragedy commented on blog/_posts/2016-11-29-intercontinental-gotober.md
> +![RGSoC goes GOTOber](/img/blog/2016/20161128-GOTOber_1.gif)<font color="grey"><small><i>Team Twitches, Team Ruby's Secret and Team LoadToCode go GOTOber</i></small></font>
This image (and all other ones in the post) need an additional image credit: either the name of the person who took the photos or the name of the team member the photo "belongs to". (i.e. if you asked a stranger to take a photo, just put down the name of the team member whose phone was used for the photo).

2016-11-28 16:29 UTC, alicetragedy commented on blog/_posts/2016-11-29-intercontinental-gotober.md
> +![RGSoC goes GOTOber](/img/blog/2016/20161128-GOTOber_1.gif)<font color="grey"><small><i>Team Twitches, Team Ruby's Secret and Team LoadToCode go GOTOber</i></small></font>
This gif is awesome, but it's also incredibly huge (>11MB!!). Please compress it using one of the compression services we link to [here](https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/CONTRIBUTING.md#images).  
Same goes for images 3, 4, and 7a.

2016-11-29 17:48 UTC, alicetragedy commented
@lilaluca could you make changes to the post as asked above? I've made a few comments as to what needs changing. Thanks!!

2016-11-29 17:54 UTC, lilaluca commented
Hey @alicetragedy, @MayarAlaa and myself are currently working it out, we are trying to do it as you suggested. 

Thanks for your help!

2016-11-29 19:58 UTC, alicetragedy commented
@lilaluca perfect, thanks! I wasn't sure if you had seen the comments already. Let me know if there is any way I can help.

2016-11-30 10:00 UTC, lilaluca commented
Hey @alicetragedy hope the requested changes are now all included. Pls let me know if otherwise.

Best

2016-11-30 10:24 UTC, alicetragedy approved these changes
looks good! I think we can merge this. Great work @lilaluca @MayarAlaa and the rest of Twitches, LoadToCode and Ruby's Secret 👍

2016-11-30 10:31 UTC, merged