Ifpair
rails-girls-summer-of-code/summer-of-code pull request #383
Opened 2017-07-17 23:47 UTC by SophieRoseMcDonald

I have updated the image file names to reflect they are from team ifpairelseunknown. I have also update the link to Adam's twitter account, previously it was not working. Lastly, I deleted an extra file which was created and not required.

2017-07-18 08:26 UTC, alicetragedy requested changes
Hi @SophieRoseMcDonald and @jnamster, thanks for your PR! ✨  Before we can merge, there are a couple of small things that need to be changed:
- adding image credits
- removing the changes made to the `Gemfile.lock` file
I've commented on these two things more in detail as inline comments on the files. 
Please update your PR accordingly when you can, and we'll be ready to publish and share your post after that!

2017-07-18 08:26 UTC, alicetragedy commented on blog/_posts/2017-07-17-ifPairElseUnknown.md
> +![Team Banner](/img/blog/2017/ifPairElseUnknown_v5.png)
please add image credits to all the images you've used in the post. “Image credits” means either a source for the images/where you got them from, or who took the photo — depending on what type of image it is. you can find more about this [here](https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/CONTRIBUTING.md#images). Please also take a look at past blog posts to see the styling that's been applied to the credits :)

2017-07-18 08:26 UTC, alicetragedy commented on Gemfile.lock
>  GEM
a little issue here — `Gemfile.lock` has been committed, which it shouldn't have. (i.e. for now we want to stick to the previous version of the `Gemfile.lock` file.) To undo this, you can: 
- rollback to the previous version of the `Gemfile.lock`
- create a new commit with that new change (i.e. the new change being the switch from your “new” `Gemfile.lock` to our old `Gemfile.lock`)
- push the new change to your branch (this should update the PR accordingly)

I hope this helps. If it doesn't, or if it seems too cryptic, please ask your coaches or supervisor for help, or ping me and I can try to help! :)

2017-07-19 04:42 UTC, SophieRoseMcDonald commented
I have made those changes. Please let me know if there is anything else that needs to be done.

2017-07-19 13:33 UTC, alicetragedy approved these changes
looks great, thank you for making those changes @SophieRoseMcDonald! And congratulations on your first contribution to the `summer-of-code` repo! ✨

2017-07-19 14:03 UTC, merged