kajas blogpost from team berlin diamonds. images were already compres…
rails-girls-summer-of-code/summer-of-code pull request #390
Opened 2017-07-25 09:18 UTC by kajatiger

…sed, I couldn't make them any smaller.

2017-07-25 10:38 UTC, carpodaster commented
@kajatiger the images are 5k x 3.5k pixels. Can you resize them to a width of about 700px? That should shed a few kilobytes.

2017-07-25 15:20 UTC, kajatiger commented
when is the blog post going to be deployed and online?

2017-07-25 20:42 UTC, alicetragedy commented
Hi @kajatiger, I will review this tomorrow morning, so if it's ready to go it will be published and shared tomorrow. :)

2017-07-26 09:32 UTC, alicetragedy commented on blog/_posts/2017-07-25-team-berlindiamonds-part-one.md
> +Since I originally come from photography and psychology, I love to connect creativity and coding. So building web apps with Rails is just the right medium for me. I also joined the Opend Tech School
minor typo: Opend -> Open

2017-07-26 09:38 UTC, alicetragedy requested changes
hey @kajatiger, thanks for your contribution! There are a couple of minor things that need changing (adding image credits, adding styling for the credits) before we merge and share the post. Would you have time to do this today still? Thanks! 🎉

2017-07-26 09:38 UTC, alicetragedy commented on blog/_posts/2017-07-25-team-berlindiamonds-part-one.md
> +- news
change category to `student-posts`

2017-07-26 09:38 UTC, alicetragedy commented on blog/_posts/2017-07-25-team-berlindiamonds-part-one.md
> +![image](../img/blog/2017/2017-07-firstday-confetti.jpg)
Could you please add an image credit for this? (i.e. who took the picture, like you did for the second picture)

2017-07-26 09:38 UTC, alicetragedy commented on blog/_posts/2017-07-25-team-berlindiamonds-part-one.md
> +![image](../img/blog/2017/2017-07-empowered-diamonds.jpg) Photo by: Markus from Absolventa
we've got a special `<div class="image-credits">` for all image credits, could you add this to the post for the two images? you can see what it looks like in other teams' blog posts :) thanks!

2017-07-26 12:49 UTC, kajatiger commented on blog/_posts/2017-07-25-team-berlindiamonds-part-one.md
> +![image](../img/blog/2017/2017-07-empowered-diamonds.jpg) Photo by: Markus from Absolventa
ah I was already wondering if there was some convention like that, thanks! I think I made all the changes now.

2017-07-26 12:50 UTC, alicetragedy approved these changes
perfect, thanks @kajatiger! this is ready to go 🎉

2017-07-26 12:50 UTC, alicetragedy commented on blog/_posts/2017-07-25-team-berlindiamonds-part-one.md
> +<div class="image-credits">Kaja at her desk / Photo by: Jen</div>
👍

2017-07-26 12:50 UTC, alicetragedy commented on blog/_posts/2017-07-25-team-berlindiamonds-part-one.md
> +<div class="image-credits">Kaja and Jen / Photo by: Markus from Absolventa</div>
👍

2017-07-26 13:45 UTC, merged