Team Gemini Blog post
rails-girls-summer-of-code/summer-of-code pull request #401
Opened 2017-08-10 18:51 UTC by aksh98

First blog post due 10th August 2017.

2017-08-13 11:38 UTC, v-thakkar requested changes

2017-08-13 11:38 UTC, nerdyvaishali commented on blog/_posts/2017-08-10-opensource-here-we-come.md
> +[Akarsha](https://github.com/aksh98) and [Ramya](https://github.com/meriki) are not your regular individuals, a dash of crazy, a drop of weird and a couple of undiscovered unusual ingredients makes t
Change "Slowly but steadily ..." -> "Slowly but steadily **they** .." , "came to realise" -> "realized"

2017-08-13 11:38 UTC, nerdyvaishali commented on blog/_posts/2017-08-10-opensource-here-we-come.md
> +### Supervisor
Add blank line after '### Supervisor'.

2017-08-13 11:38 UTC, nerdyvaishali commented on blog/_posts/2017-08-10-opensource-here-we-come.md
> +Time indeed flies. We’ve already sifted through the large code base, understanding it, made small PRs here and there, learnt git, understand what a frontend architecture like react does and realise t
If you want to go for past tense then do that for all phrases here ["understand -> understood" ].
Also, change "realise the effort that a community does ..." -> " **Realized** **an** effort community **puts** ..."

2017-08-13 11:38 UTC, nerdyvaishali commented on blog/_posts/2017-08-10-opensource-here-we-come.md
> +title: Open source, here we come!
Hi, Thanks for your PR. :) Few minor changes are needed. Check out the comments below.

2017-09-01 00:24 UTC, aksh98 commented
Hi @nerdyvaishali 
Updated the blog post. Kindly review it again.

2017-09-01 16:10 UTC, v-thakkar requested changes

2017-09-01 16:10 UTC, nerdyvaishali commented on blog/_posts/2017-08-10-opensource-here-we-come.md
> +created_at: Monday August 10 2017
Hi, can you please change the date to September 4, 2017? Change permalink field as well.

2017-09-01 16:10 UTC, nerdyvaishali commented on blog/_posts/2017-08-10-opensource-here-we-come.md
> +# Why Susi AI?
Writing about SUSI AI project and then about sci-kit image mentors in introduction of teams looks bit odd. Can you please add the section 'our projects' or your 'What we’ve done so far and some unexpected events' section over here? There you can talk about susi AI project in 2-3 lines, your experience and what is the current situation now. And after that section you can have the same section of introducing the team as it is. You can also have 'future plan' kind of small section at the end, if you want to add that.

2017-09-03 03:02 UTC, aksh98 commented
@nerdyvaishali seems fine now ?

2017-09-03 06:30 UTC, v-thakkar requested changes

2017-09-03 06:30 UTC, nerdyvaishali commented on blog/_posts/2017-09-04-opensource-here-we-come.md
> +Time indeed flies. We’ve already sifted through the large code base, understood it, made small PRs here and there, learnt git, understood what a frontend architecture like react does and realized the
Post looks better to me now. Only one concern here. It's not clear about which project you are talking here. It's totally fine to mention which project was assigned to you previously, what you learnt/worked on and which project you will be working on now. Can you please add project names and things accordingly? Thanks.

2017-09-04 12:57 UTC, v-thakkar approved these changes

2017-09-04 12:57 UTC, merged