Contributing to issue #289
rails-girls-summer-of-code/summer-of-code pull request #404
Opened 2017-08-15 14:28 UTC by frefell

Update image credits (#289) for blogposts between 2015-07-23 and 2015-10-30

2017-08-16 18:06 UTC, alicetragedy requested changes
Hi @frefell, wow, thank you so much for this contribution! It's so exciting to have this long open issue be taken care of ❤️ 
Before I merge this I'd like you to change something — I've left a comment about it in one of the files. If you have any question about this, don't hesitate to ping me, I'm always happy to help.

2017-08-16 18:06 UTC, alicetragedy commented on blog/_posts/2015-07-23-rubyherzlein.md
> +<div align="center" class="image-credits">Rubyherzlein Team + extended Team: Erik, Duana, Hannes  (Image: Rubyherzlein Team) </div>
could you remove the `align="center"` bit from all the files? Unfortunately some of the last contributors to blog posts seem to have added that, but it doesn't belong in there. Thank you so much!

2017-08-17 07:50 UTC, frefell commented on blog/_posts/2015-07-23-rubyherzlein.md
> +<div align="center" class="image-credits">Rubyherzlein Team + extended Team: Erik, Duana, Hannes  (Image: Rubyherzlein Team) </div>
Hei, thanks for your review :) I will take care of that.

2017-08-21 13:29 UTC, alicetragedy commented
@frefell thanks for starting to make the changes! I see there's still a couple of blog posts that haven't been updated — would you like to just ping me directly in here when you're done, so that I can review it all and merge? Thanks! 🙌

2017-08-21 14:52 UTC, frefell commented
@alicetragedy Yes I was planning that, because I will need some more days to finish this :)

2017-08-21 14:57 UTC, alicetragedy commented
Great! Just wanted to make sure you know you can ping me when you're done (or if you need anything). 😇

2017-08-29 09:20 UTC, alicetragedy commented
Hey @frefell, were you able to make more changes to the posts? I'd love to merge this soon — maybe there is something I can do to help?

2017-08-29 13:21 UTC, frefell commented
Hey, @alicetragedy! 
I was very busy last week, but managed to change everything in the blogposts between 2015-07-23 and 2015-10-30, as in the first pull request, so I think this could be merged now.

If I find time to work on the older blogposts, I will create a new pull request. :)

2017-08-30 15:05 UTC, alicetragedy requested changes
Awesome, this looks great! there are a couple of things that need changing (a `<p>` tag that needs removing and a missing letter). These are all minor things, so if you can't make the changes, let me know and I will make them myself after merging. <3

2017-08-30 15:05 UTC, alicetragedy commented on blog/_posts/2015-08-07-fanxhe-team-is-broadcasting-from-rgsoc.md
>  <p align="center">
I think this line can be removed as well :)

2017-08-30 15:05 UTC, alicetragedy commented on blog/_posts/2015-09-16-alster-hamburgers-code-review.md
> +<div class="image-credits">hat learning felt like at times... Illustration: Anke </div>
there's a `W` missing here at the beginning of the sentence 😇

2017-08-30 15:05 UTC, alicetragedy commented on blog/_posts/2015-09-24-A-Tale-of-Sweet-Cocoa-with-Gems.md
> +<div class="image-credits">Members of CocoaPods getting together for dinner after AltConf. Photo by Karla </div>
Thank you for fixing this typo 🙌

2017-08-31 14:33 UTC, frefell commented
hei again, @alicetragedy. I think I found the small errors you mentioned, and everything should be nice now :)

2017-09-01 10:04 UTC, alicetragedy approved these changes
Whoohoo! Awesome @frefell, looks like we're ready to ship this. 🙌

2017-09-01 10:04 UTC, merged

2017-09-01 10:05 UTC, alicetragedy commented
Congratulations on your very first contribution to our website, @frefell! This was a lot of tedious work and it's sooooo helpful to have these changes, so thank you so much for taking the time to improve these posts for us. 💖 💪 💻