Blog 2 for ifPairElseUnknown - Sept 11 2017
rails-girls-summer-of-code/summer-of-code pull request #407
Opened 2017-09-06 02:17 UTC by jnamster

2017-09-06 15:11 UTC, v-thakkar requested changes

2017-09-06 15:11 UTC, nerdyvaishali commented on blog/_posts/2017-09-11-ifPairElseUnknown-final-month.md
> +### __You can find here__
Hi, Thanks for sending a PR before scheduled date. The blog post looks good to me. :)

Only comment I've is I think you meant 'You can find **us** here' in the above line. Can you please fix it?

2017-09-07 14:16 UTC, jnamster commented
Thanks for the review. I have amended 'You can find us here'. Also made some amendments to the link to our coach and centred the gifs.

2017-09-08 15:27 UTC, v-thakkar approved these changes

2017-09-08 15:47 UTC, merged

2017-09-08 15:48 UTC, nerdyvaishali commented
Thanks for the changes. I've published the blog. :)