Second blog post of Team fusion
rails-girls-summer-of-code/summer-of-code pull request #416
Opened 2017-09-14 11:26 UTC by kalpanibhagya

2017-09-14 11:33 UTC, Janakshi28 commented
Request for review : @alicetragedy

2017-09-16 17:41 UTC, Janakshi28 commented
Hi @nerdyvaishali , is there any changes that we have do with this PR?

2017-09-18 04:03 UTC, v-thakkar requested changes

2017-09-18 04:03 UTC, nerdyvaishali commented on blog/_posts/2017-09-14-a-song-like-summer.md
> +created_at: Thu Sep 14 2017
Hi, thanks for the PR. Good job on improving many things by your own. Thanks. :) I just have 2 small comments and then blog will be ready to publish. Can you please change a date to Tue September 19, 2017 everywhere?

2017-09-18 04:03 UTC, nerdyvaishali commented on blog/_posts/2017-09-14-a-song-like-summer.md
> +We believe, we can do more after this summer. After RGSoC, we would love to continue our contributions to **OpenDF**. And we are even planning to participate in next year’s RGSoC. See how impressed a
You can't participate in RGSoC again. Can you just remove that line? :)

2017-09-18 04:03 UTC, nerdyvaishali commented on blog/_posts/2017-09-14-a-song-like-summer.md
> +Follow us on Twitter at [@TeamFusionJK](https://twitter.com/TeamFusionJK), [@JanakshiDulanga](https://twitter.com/JanakshiDulanga) and [@KbKalpani](https://twitter.com/KbKalpani)
Put full stop(.) after 1st statement.

2017-09-19 04:02 UTC, Janakshi28 commented
Hi @nerdyvaishali , we made the changes as you requested. :)

2017-09-19 05:19 UTC, v-thakkar approved these changes

2017-09-19 05:19 UTC, nerdyvaishali commented
Thanks for the changes @Janakshi28 . :)

2017-09-19 05:20 UTC, merged

2017-09-19 09:47 UTC, Janakshi28 commented
Hi @nerdyvaishali ,

There's another minor typo with our blog post. Once it was published only we saw it. 
https://github.com/Janakshi28/RGSoC--Images/blob/master/Screenshot%20(38).png

The sentences in this snap should be in point form, but there are not due to some error with the markdown usage. Can we send another PR with the fix for that?

2017-09-19 10:12 UTC, alicetragedy commented
@Janakshi28 yes, please do send another PR with the fix — however make sure your local fork and version is synced before you do that, otherwise you might encounter some merge conflicts that will need fixing. Thanks in advance!

2017-09-19 10:59 UTC, nerdyvaishali commented
Thanks for noticing @Janakshi28 . It's a markdown space issue and I missed it. Sure, send a PR and we will merge it.

2017-09-19 11:01 UTC, Janakshi28 commented
@nerdyvaishali , I sent a new PR for this Fix #422 .

Thank you :)