Rails gyn last blog post
rails-girls-summer-of-code/summer-of-code pull request #426
Opened 2017-09-22 19:23 UTC by branquinhoaa

Submit Rails Girls Last Blog Post

2017-09-27 06:44 UTC, v-thakkar requested changes

2017-09-27 06:44 UTC, nerdyvaishali commented on blog/_posts/2017-09-8-railsgyn-lastblogpost.md
> +created_at: Fri September 22 2017
Hi, thanks for the PR. Your blogpost is scheduled to be published on Thursday September 27, 2017. Can you please update the date everywhere?

2017-09-27 06:44 UTC, nerdyvaishali commented on blog/_posts/2017-09-8-railsgyn-lastblogpost.md
> +That is was a challenge do with you, it makes you find out how far you can go.
This sentence 'That is was a challenge do with you, it makes you find out how far you can go' looks bit odd. Can you rephrase it?

2017-09-27 06:44 UTC, nerdyvaishali commented on blog/_posts/2017-09-8-railsgyn-lastblogpost.md
> +After finish the conference milestone, we have decided to start a community milestone and we still are working on it. Even if we did not finish it until september/30 we will finish it!
Change 'finish' -> 'finishing', 'start a community'->'start **on** a community'

2017-09-27 06:44 UTC, nerdyvaishali commented on blog/_posts/2017-09-8-railsgyn-lastblogpost.md
> +## What do we learn?
Change 'do'->'did'

2017-09-27 06:44 UTC, nerdyvaishali commented on blog/_posts/2017-09-8-railsgyn-lastblogpost.md
> +Well, this summer was a great learning experience for us, our mentors were fantastic with your code reviews, it makes us grow up a lot. During this summer we can learn more about tests with RSpec, us
This line: 'our mentors were fantastic with your code reviews, it makes us grow up a lot looks bit odd too.' Can you change/rephrase it as well?

2017-09-27 06:44 UTC, nerdyvaishali commented on blog/_posts/2017-09-8-railsgyn-lastblogpost.md
> +Besides knowledge, the program brought us a lot of local visibility. Due to the program, one of the local companies has contacted us to offer us support to promote events. Also, this same company cal
In 'contacted us to offer us support', remove one '**us**'. How about: '.has contacted us to offer support **for promoting** events' ? 
Change 'calls us'->'has called us'

2017-09-27 18:30 UTC, branquinhoaa commented
Thanks for your review @nerdyvaishali! I think now it is ok!

2017-09-28 18:07 UTC, v-thakkar approved these changes

2017-09-28 18:15 UTC, merged