2nd Blog Post for TeamGemini
rails-girls-summer-of-code/summer-of-code pull request #432
Opened 2017-10-04 23:42 UTC by aksh98

This is our second blog post.

2017-10-04 23:44 UTC, aksh98 commented
Can someone please confirm if the iframe embed code works or not?

2017-10-05 16:11 UTC, v-thakkar requested changes

2017-10-05 16:11 UTC, v-thakkar commented on blog/_posts/2017-10-05-TeamGemini-Happy-ending-yet-not-the-end.md
> +created_at: Sun Oct 05 2017
Hi, thanks fro the PR. Correct a day here. It should be Thursday instead of Sunday.

2017-10-05 16:11 UTC, v-thakkar commented on blog/_posts/2017-10-05-TeamGemini-Happy-ending-yet-not-the-end.md
> +What a roller coaster ride it has been! It is disheartening to realize how soon it has ended. RGSoC is one of the most beautiful communities we could ever be a part of at this stage. We really learnt
Change communities -> community. Use comma instead of semicolon for the consistency in a single sentence.

Last sentence needs a change: '... by helping out and supporting **more people to get into the tech**'

2017-10-05 16:11 UTC, nerdyvaishali commented on blog/_posts/2017-10-05-TeamGemini-Happy-ending-yet-not-the-end.md
> +We would not be able to thank RGSoC enough for all we learned through this summer. Let alone be the fact that we are now comfortable reading huge codebases (Yes, we got the opportunity to work with t
Add following changes in this sentence: 'Besides contributing to open source, we learnt new tools and technologies, and improved our skill-set. '

2017-10-05 16:11 UTC, nerdyvaishali commented on blog/_posts/2017-10-05-TeamGemini-Happy-ending-yet-not-the-end.md
> +At one such opensource meetup, [Akarsha](https://twitter.com/akarsha98) also met the co-founder of her early-stage startup ‘Invadex’ which she is going to represent in the Alpha program of Web-summit
Remove one the in this sentence: 'the **“The Largest Tech Conference in the World”**'. 

This 'took to research' looks bit odd. Rephrase it.

2017-10-05 16:11 UTC, nerdyvaishali commented on blog/_posts/2017-10-05-TeamGemini-Happy-ending-yet-not-the-end.md
> +<iframe src="https://giphy.com/embed/xUPGcxpCV81ebKh7Vu" width="480" height="320" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/studiosoriginals-xUPG
Related to your comment regarding iframe, I've tested this blog post. And it works. But it's aligned to the left. Align both giphy and credit in the center.

Also, generally speaking, it is not a good practice to send PR before testing it locally. It adds extra burden on reviewers/maintainers. Many communities don't consider this as a good habit and bans contributors from the projects too. Just keep in mind for the next time. :)

2017-10-05 16:11 UTC, nerdyvaishali commented on blog/_posts/2017-10-05-TeamGemini-Happy-ending-yet-not-the-end.md
> +Andd we are *Organizing [Django Girls Lisbon](https://djangogirls.org/lisbon) on 5th November*.
Typo here: 'And'

2017-10-05 16:11 UTC, nerdyvaishali commented on blog/_posts/2017-10-05-TeamGemini-Happy-ending-yet-not-the-end.md
> +If you are there in Lisbon during that time, come join us! :). Also, next, we’ll organize Django Girls, Delhi in December/January. And next to this, we’ll be going for Rubyconf in February’18. Also,
Add will here: 'we **will** continue to learn'

2017-10-05 22:42 UTC, aksh98 commented on blog/_posts/2017-10-05-TeamGemini-Happy-ending-yet-not-the-end.md
> +What a roller coaster ride it has been! It is disheartening to realize how soon it has ended. RGSoC is one of the most beautiful communities we could ever be a part of at this stage. We really learnt
I believe communities is grammatically correct. And the same for semicolon.

2017-10-06 04:51 UTC, nerdyvaishali commented on blog/_posts/2017-10-05-TeamGemini-Happy-ending-yet-not-the-end.md
> +What a roller coaster ride it has been! It is disheartening to realize how soon it has ended. RGSoC is one of the most beautiful communities we could ever be a part of at this stage. We really learnt
Yes, you're right about communities. That was my mistake. Though semicolon and comma can be used interchangeably I believe. But that's ok.

2017-10-06 05:23 UTC, v-thakkar requested changes

2017-10-06 05:23 UTC, nerdyvaishali commented on blog/_posts/2017-10-05-TeamGemini-Happy-ending-yet-not-the-end.md
> +<iframe src="https://giphy.com/embed/l3q2u6MXJJEKiTZIY" width="700" height="480" style="float:initial" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
With new changes, credits are missing. Add the credits using 'image-credits' class and align it in the center for both GIFs.

2017-10-06 05:23 UTC, nerdyvaishali commented on blog/_posts/2017-10-05-TeamGemini-Happy-ending-yet-not-the-end.md
> +Andd we are *Organizing [Django Girls Lisbon](https://djangogirls.org/lisbon) on 5th November* to let more girls fall in love with programming and open-source..
Typo for 'And' is still there. Or do you mean any internet abbreviation here which I don't understand?

2017-10-07 07:38 UTC, v-thakkar requested changes

2017-10-07 07:38 UTC, nerdyvaishali commented on blog/_posts/2017-10-05-TeamGemini-Happy-ending-yet-not-the-end.md
> +<iframe src="https://giphy.com/embed/l3q2u6MXJJEKiTZIY" width="700" height="480" style="float:initial" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p align="center"><cite>Source: GIP
Like I said in my previous reviews for this PR, please use 'image-credits' class for credits. We prefer to use it for the consistency purpose.

2017-10-07 13:32 UTC, v-thakkar approved these changes

2017-10-07 13:36 UTC, merged