Issue #389- fixed Gem dependencies
rails-girls-summer-of-code/summer-of-code pull request #483
Opened 2018-02-26 22:18 UTC by wiseemily88

Added Ruby version to Gemfile, and  updated the ReadMe for those using a RVM specifying Ruby version and any potential issues with an outdated Bundler on your local machine. PR submitted with the help from @izaxveta and @erikaannesmith

2018-03-07 15:03 UTC, alicetragedy requested changes
Hi @wiseemily88, thank you so much for looking into this issue and providing a fix! It's awesome, and I'm so grateful for these changes you've made 🙌 🎉  
I've added a couple of minor suggestions of things that would need changing before we can merge this. Please let me know if you have any questions about my comments or if anything is unclear!

2018-03-07 15:03 UTC, alicetragedy commented on CONTRIBUTING.md
> +Both .ruby-version and Gemfile handle the Ruby version (2.1.5) for this application. Users with or without a RVM (Ruby Versioning Manager) should be able to interact and contribute to the code base.
two comments about this section:  
- I don't think it's necessary to specify the exact Ruby version here, you just remove the `(2.1.5)` — that way we could avoid the README becoming accidentally outdated the next time we update our Ruby version. What do you think?
- I'd suggest to make the bit about Ruby versioning more general, something along the lines of:
"User who don't use a tool to manage Ruby versions (such as [RVM](https://rvm.io/) or [rbenv](https://github.com/rbenv/rbenv)) should be able to [...]". This way we avoid to specifically show preference about a single tool.

2018-03-07 15:03 UTC, alicetragedy commented on Gemfile
> +ruby '~> 2.1.5'
A suggestion: replace this line with `ruby File.read(".ruby-version")`.
This way, we'd only need to update the ruby version in the `.ruby-version` file, and the Gemfile would follow. :)

2018-03-07 15:03 UTC, alicetragedy commented on Gemfile
> +ruby '~> 2.1.5'
ah and also:
while I don't actually know the reason for it (or *if* there is a reason for it) the convention in a Gemfile is usually to put the Ruby version right under the `source 'https://rubygems.org'` line. Could you move it up there?

2018-06-11 08:52 UTC, alicetragedy commented
hi @wiseemily88 👋 
I'd love to merge your changes and implement those improvements you suggested! In order to do that, I'd need you to review my suggestions in the PR review above. Please me know if you have any questions.
If you think you won't have time, or if you are not interested in doing this anymore, please leave a comment in here — that way I can cherry-pick your commits (or merge your PR and make those additional changes myself, if that's ok with you). 🎉

2018-06-11 19:02 UTC, wiseemily88 commented
@alicetragedy Sorry this took so long to address!! look forward to contributing more and at a quicker pace in the future :)

2018-06-13 13:41 UTC, alicetragedy approved these changes

2018-06-13 13:42 UTC, alicetragedy commented
This is so great @wiseemily88 — thank you so much! So happy to be able to merge this and implement your awesome changes into our project 🎉 
We'd love to have you contribute again, I'm always glad to see contributors helping out. 🙌 
Congrats on your first contribution to the RGSoC project!

2018-06-13 13:43 UTC, merged