First blog post
rails-girls-summer-of-code/summer-of-code pull request #518
Opened 2018-07-07 21:13 UTC by milaaraujo

Camila and Stefanni

2018-07-14 09:40 UTC, v-thakkar requested changes

2018-07-14 09:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-07-brazilian-team.md
> +I am a millennial that likes to how to cook (gasp) and loves coding, cats, playing sports and chocolate. I moved to Vancouver in January because my husband received a job offer to work here and we br
Hi @milaaraujo ! Thanks for the PR. See the comments below.

The sentence needs a little bit modification. '... am a millennial that likes how to cook, loves coding, cats ...'.

2018-07-14 09:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-07-brazilian-team.md
> +Thanks, RGSoc organizers for providing these mediums for us to find a teammate :)
Change RGSoc -> RGSoC :)

2018-07-14 09:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-07-brazilian-team.md
> +** Coaches: **
Did you intend to put these titles [coaches, mentor etc] in bold? Then you'll need to remove the space between asterisks and text. If not, then it's fine.

Also, for the consistency purpose either use all titles with colon or without colon.

2018-07-14 17:34 UTC, milaaraujo commented
Hi, @nerdyvaishali! Thank you for reviewing our blog post. I've committed a new version.

2018-07-16 13:29 UTC, v-thakkar approved these changes

2018-07-16 13:30 UTC, nerdyvaishali commented
Thanks @milaaraujo ! Looks good to me.

2018-07-17 13:29 UTC, anasofiapinho commented
First student's blog post to be merged! Go Team Brazilian Housewives Coding! 🙌 cc/ @milaaraujo

2018-07-17 13:31 UTC, merged

2018-07-17 18:53 UTC, milaaraujo commented
Thank you, @anasofiapinho!