Added Teampopcorn's first blog post and photos
rails-girls-summer-of-code/summer-of-code pull request #519
Opened 2018-07-08 14:21 UTC by sleepypioneer

2018-07-09 10:01 UTC, sleepypioneer commented
@anasofiapinho I have failed checks for the deploy preview. Its because I dont have ruby set up on my home machine, is it ok without this check? I will set it up now incase it's not or can commit again from the coaching company in two hours.

2018-07-17 12:57 UTC, v-thakkar requested changes

2018-07-17 12:57 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-welcome-to-team-popcorn.md
> +permalink: blog/2018-07-09-welcome-to-team-popcorn.md
Hi @sleepypioneer! Thanks for the PR. I just have minor comments. You don't need markdown file extension (.md) for 'permalink'.

2018-07-17 12:57 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-welcome-to-team-popcorn.md
> +categories: student-posts
Just to maintain consistency across files and format for the posts, can you just change how you have declared categories parameter like below:

```
categories:
- student-posts
```

2018-07-17 16:19 UTC, sleepypioneer commented
Hi @nerdyvaishali we have made those changes :)

2018-07-19 17:36 UTC, v-thakkar approved these changes

2018-07-23 12:51 UTC, merged