Team $we init, introductory post.
rails-girls-summer-of-code/summer-of-code pull request #521
Opened 2018-07-09 07:55 UTC by Rahmeen14

2018-07-25 17:40 UTC, v-thakkar requested changes

2018-07-25 17:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-$we-init-introductory-post.md
> +# Dreams come true !
Hi @Rahmeen14 ! Thanks for the PR. Please check the other blog posts for the proper markdown format. We need the whole set of parameters at the start.

2018-07-25 17:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-$we-init-introductory-post.md
> +
Please add image description and use image-credits class to add credits.

2018-07-25 17:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-$we-init-introductory-post.md
> +* She has this habit of quoting random Shakespearean, Tagore and Frost quotations and then justifying their relevence in the ongoing context.
Fix the typo here: 'relevance'.

2018-07-25 17:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-$we-init-introductory-post.md
> +A graduate from IIIT Allahabad, Saptak is a passioante open source contributor. A GSoC '16 student with FOSSASIA, Saptak is currently working as a Software Developer with Gitcoin. We're super excited
Fix the typo here: 'passionate'

2018-07-25 17:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-$we-init-introductory-post.md
> +Our bachmate and a 2018 GSocer, Manish is a very good friend of ours. Being a CodeHeat winner under FOSSASIA, he is extremely passionate about contributing to open source and loves to help others too
Fix the typo here: 'batchmate'

2018-07-25 17:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-$we-init-introductory-post.md
> +A two-time GSoCer a 2017 passout from Delhi Technological University, Saksham is always happy to help. And not most people will believe but we found him on Quora (Yay, Rahmeen's infinite quora scroll
Fix the typo here: 'experience'

2018-07-25 17:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-$we-init-introductory-post.md
> +A 2016 batch passout from our college, Divjot is a full-time Software Developer at Swiggy. We wouldn't be exaggerating if we say that he's the absolute best senior one could ask for. From resolving o
Change insta -> instagram

2018-07-25 17:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-$we-init-introductory-post.md
> +They are both GitHub employees and maintainers of probot for quite some time now. They have been amazing mentors and have always offered helped, generously. :')
Change 'offered helped -> offered help.

2018-07-25 17:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-$we-init-introductory-post.md
> +Even before the project list was announced, we were perusing all the then ‘pending’ projects and that was when we found ‘Probot’ and were blown away by its idea almost immediately. We were completely
' .. after the final projects announcement ..' sounds bit weird. May be change it to '.. after the announcement of final projects.. '. :)

2018-07-25 17:40 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-$we-init-introductory-post.md
> +* Completely opposite to her partner Rahmeen who has an amazing memeory, she is quite forgetful and would be found digging up stuffs.
Fix the typo here: 'memory'.

2018-07-27 21:06 UTC, Rahmeen14 commented
Hey @nerdyvaishali ! I have made the said changes. Please have a look whenever you find time! Thanks :)

2018-08-02 17:04 UTC, v-thakkar approved these changes

2018-08-02 17:06 UTC, v-thakkar requested changes

2018-08-02 17:06 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-$we-init-introductory-post.md
> +# Dreams come true !
Hi @Rahmeen14 ! Permalink should be the same as the file name. Please check other files for the example. Everything else looks good to me.

2018-08-03 12:31 UTC, v-thakkar approved these changes

2018-08-03 12:32 UTC, nerdyvaishali commented
Nevermind @Rahmeen14, I've changed it for now as we wanted to publish this post by today. But make sure to follow the blog post guide from the next time. Thanks. :)

2018-08-03 16:28 UTC, merged

2018-08-03 16:51 UTC, Rahmeen14 commented
Acknowledged! Will take care from next time.