Blog
rails-girls-summer-of-code/summer-of-code pull request #523
Opened 2018-07-09 11:42 UTC by prateksha

Introducing Team Rubies 2018!

2018-07-19 17:49 UTC, v-thakkar requested changes

2018-07-19 17:49 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-IntroducingTeamRubies.md
> +
Hi @prateksha ! Thanks for the PR. Extra one line space at the start is unnecessary. Please remove it.

2018-07-19 17:49 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-IntroducingTeamRubies.md
> +permalink: blog/2018-07-09-introducing-team-rubies
Permalink should be same as file name [it is case-sensitive]. :)

2018-07-19 17:49 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-IntroducingTeamRubies.md
> +![FirstContact](/img/blog/2018/2018-07-09-TeamRubies-FirstContact.png)
Please add pic credits like other images for this photo/screenshot [in the text].

2018-07-19 17:49 UTC, nerdyvaishali commented on blog/_posts/2018-07-09-IntroducingTeamRubies.md
> +![HappyUs](/img/blog/2018/2018-07-09-TeamRubies-HappyUs.jpeg)
Pic description and pic credits missing. :)

2018-07-20 04:27 UTC, prateksha commented
@nerdyvaishali Made all the required changes!

2018-07-25 17:13 UTC, v-thakkar approved these changes

2018-07-30 14:32 UTC, merged