Create Hola, Amigos.md
rails-girls-summer-of-code/summer-of-code pull request #524
Opened 2018-07-09 12:01 UTC by avneet14027

Team Sectumsempra blog.
RGSoC 2018

2018-07-25 17:54 UTC, v-thakkar requested changes

2018-07-25 17:54 UTC, nerdyvaishali commented on blog/_posts/Hola, Amigos.md
> +
Hi @avneet14027  ! Thanks for the PR. Please check the other blog posts for the proper markdown format. We need the whole set of parameters at the start.

2018-07-25 17:54 UTC, nerdyvaishali commented on blog/_posts/Hola, Amigos.md
> +
No need of extra blank lines. Please remove them.

2018-07-25 17:54 UTC, nerdyvaishali commented on blog/_posts/Hola, Amigos.md
> + ![Alt Text](https://github.com/avneet14027/Miscellaneous/blob/master/WhatsApp%20Image%202018-07-09%20at%205.13.08%20PM.jpeg)
Add image description and image-credits class for adding image credits. Same for the GIF at the bottom.

2018-07-25 17:54 UTC, nerdyvaishali commented on blog/_posts/Hola, Amigos.md
> +After a thorough application process, a long wait and an interview, we thought we might just be able to make it through, and were eagerly waiting for that one “Welcome to RGSoC” email. In time, an em
Change victorious -> victoriously.

2018-07-25 17:54 UTC, nerdyvaishali commented on blog/_posts/Hola, Amigos.md
> +I have had this habit of imaginng things in my head, things that I aspire to do and achieve, but the results are not always the way I expected them to be. But then, I take a deep breath and reflect b
Fix the typo here: 'imagining'.

2018-07-25 17:54 UTC, nerdyvaishali commented on blog/_posts/Hola, Amigos.md
> + - [**Louis Jenkins**](https://louisjenkinscs.github.io/): He is a  recent Computer Science graduate from Bloomsburg interests and experience in the low-level areas such as compilers, operating syste
Not sure why you have added the same website/linkedin links twice. Please remove the links with 'Source' texts.

2018-07-25 17:54 UTC, nerdyvaishali commented on blog/_posts/Hola, Amigos.md
> +- [**Lydia Duncan**](https://github.com/lydia-duncan)
It looks weird to have small introduction text for everyone except this person. Please either add for all or none.

2018-07-26 15:48 UTC, avneet14027 commented
Hi Vaishali,
I have made the changes as suggested by you. 
Thanks,
Avneet

2018-08-03 06:08 UTC, v-thakkar approved these changes

2018-08-03 06:13 UTC, v-thakkar requested changes

2018-08-03 06:13 UTC, nerdyvaishali commented on blog/_posts/Hola, Amigos.md
> +**title:** We solemnly swear we’re upto no good!
Hi @avneet14027 ! You would need to use exact format as used in other files for declaring parameters. For example, no use of '**', permalink same as file name etc. Please check and test them locally.

2018-08-03 06:13 UTC, nerdyvaishali commented on blog/_posts/Hola, Amigos.md
> + ![Alt Text](https://github.com/avneet14027/images/blob/master/2018-07-09-team-sectumsempra-blog-teampic.jpeg)
Please add image description as well. For example, who is in the image etc. And then in brackets, you can write about image source. As the blog post is from a team and not a single person, 'self' is a confusing word as a source. You need to specify the name or device etc.

2018-08-06 19:12 UTC, avneet14027 commented
Hey @nerdyvaishali , I have updated the file as per the changes requested!
Thanks,
Avneet

2018-08-07 13:44 UTC, v-thakkar approved these changes

2018-08-07 14:44 UTC, merged