Team DelSquared Blogpost
rails-girls-summer-of-code/summer-of-code pull request #526
Opened 2018-07-10 18:03 UTC by arushi019

2018-08-03 06:19 UTC, v-thakkar requested changes

2018-08-03 06:19 UTC, v-thakkar commented on blog/_posts/DelSquared_RGSoC_blogpost.md
> +﻿**DelSquared: Rails Girls Summer of Code 2018 and Us**
Hi @arushi019  ! Thanks for the PR. Please check the other blog posts for the proper markdown format. We need the whole set of parameters at the start.

2018-08-03 06:19 UTC, v-thakkar commented on blog/_posts/DelSquared_RGSoC_blogpost.md
> +We worked together during the application process and all the revisions and the reviews were really smooth. Since the commencement of the internship, Brihi and Shravika have been talking to us about
Here, as we are going to publish your blog post in upcoming week(s), can you please also change the narrative here about the first call as by now I think it has already happened. Also, no need to specify about thanking me for the extension in the blog post. :)

2018-08-05 12:50 UTC, arushi019 commented
Hi @nerdyvaishali I have made the changes as per the review. Kindly check :)

2018-08-09 15:19 UTC, v-thakkar approved these changes

2018-08-09 15:23 UTC, v-thakkar requested changes

2018-08-09 15:23 UTC, nerdyvaishali commented on blog/_posts/DelSquared_RGSoC_blogpost.md
> +---
Hi @arushi019 ! No need of the blank line at the start of an article and blank spaces at the start of parameters. It changes the format. Please test the blog post for markdown format. You can test it in some online tool also if you don't want to run the site locally.

2018-08-09 15:23 UTC, nerdyvaishali commented on blog/_posts/DelSquared_RGSoC_blogpost.md
> + **DelSquared: Rails Girls Summer of Code 2018 and Us**
Please user markdown style headers and add blank lines in between each header and text. The comment applies to all titles and text in the whole file.

2018-08-10 09:16 UTC, arushi019 commented
Hi! 
I think this time it is okay and matches with the required format. @nerdyvaishali I am really sorry for troubling you again but please review :)

2018-08-10 09:25 UTC, v-thakkar approved these changes

2018-08-10 09:37 UTC, nerdyvaishali commented
@arushi019 No problem. Looks good to me. Thanks!

2018-08-10 16:37 UTC, merged