Team 101 Days of Summer : Blog Post 2
rails-girls-summer-of-code/summer-of-code pull request #543
Opened 2018-09-16 14:08 UTC by nupurbaghel

We have completed our blog post 😄 !! cc @paavininanda

2018-10-15 10:24 UTC, v-thakkar requested changes

2018-10-15 10:24 UTC, v-thakkar commented on blog/_posts/2018-09-15-101daysofsummer-blog2.md
> +title: An enriching journey, Summers’ 2018 :: Team 101 Days of Summer
Hi @nupurbaghel ! Thanks for the PR. Some minor comments here. 

Markdown doesn't seem to be transforming "::" into HTML properly. Please use "-" or any other symbol for the title.

2018-10-15 10:24 UTC, v-thakkar commented on blog/_posts/2018-09-15-101daysofsummer-blog2.md
> +categories: student-posts
To be consistent with other files, Please declare categories in the line below. You can check other posts.

2018-10-15 10:24 UTC, v-thakkar commented on blog/_posts/2018-09-15-101daysofsummer-blog2.md
> +![In our happy workspace (our hostel room :P) with tons of memories from this Summer with Servo and RGSoC ❤️ We wish we had taken a picture with Rakhi and Josh from one of our remote calls :P We’ll t
Add image description and use image-credits class to add image credits for this picture. Check the output before pushing the revised commit.

2018-10-15 10:24 UTC, v-thakkar commented on blog/_posts/2018-09-15-101daysofsummer-blog2.md
> +![how to use match example](/img/blog/2018/rgsoc-2019-09-15-101daysofsummer-blog2-02.jpeg)
Add image description and image credits here as well.

2018-10-15 10:24 UTC, v-thakkar commented on blog/_posts/2018-09-15-101daysofsummer-blog2.md
> +- In total we got **20 PR’s** merged by the end of RGSoC. Approximately 10 each for the both of us. Hooray!!
Do you have single link where people can see all your contributions/commits? I think it'll be good to put that link somewhere here.

2018-10-18 06:29 UTC, nupurbaghel commented on blog/_posts/2018-09-15-101daysofsummer-blog2.md
> +- In total we got **20 PR’s** merged by the end of RGSoC. Approximately 10 each for the both of us. Hooray!!
We have 2 links, one for each of us. I can put that if required..

2018-10-26 12:51 UTC, v-thakkar approved these changes

2018-11-06 05:51 UTC, merged