2nd Blog for girls code Mk
rails-girls-summer-of-code/summer-of-code pull request #547
Opened 2018-09-17 09:17 UTC by gtl90

2018-09-18 11:59 UTC, gtl90 commented
img path wrong
 white space added to headings to format correctly
added bullet list at top

2018-09-18 12:23 UTC, gtl90 commented
Just a little more glitter - going to miss RGSoC

2018-09-23 17:33 UTC, v-thakkar requested changes

2018-09-23 17:33 UTC, nerdyvaishali commented on blog/_posts/2018-09-17-Code-2-a-good-summer.md
> +Anna
Hi, 'Anna' is there for 2 times. Did you mean 'Ana Sofia'? And did you also mean 'Vaishali', as I don't any RGSoC organizer named Valisha. :)

2018-09-23 17:33 UTC, nerdyvaishali commented on blog/_posts/2018-09-17-Code-2-a-good-summer.md
> +![RGSoC Glitters](/img/blog/2018/RGSOC_glitters.jpg)
The image seems to be broken for some reason. Please fix that.

2018-09-23 17:33 UTC, nerdyvaishali commented on blog/_posts/2018-09-17-Code-2-a-good-summer.md
> +permalink: blog/2018-07-25-Code-2-a-good-summer
Hi @gtl90 ! Thanks for your PR. Lovely blog post. Please check the bunch of minor comments I have. 

Filename and permalink needs to be the same.

2018-09-24 11:20 UTC, gtl90 commented
I have updated the pull request not sure if this is correct way of doing or whether I should create a new pull request.  Let me know.  Thank you Vaishali :)

2018-09-24 11:35 UTC, nerdyvaishali commented
That's the correct way @gtl90 ! Looks good to me now. Thanks!

2018-09-24 11:35 UTC, v-thakkar approved these changes

2018-09-26 09:19 UTC, merged