Team akaringular final blog
rails-girls-summer-of-code/summer-of-code pull request #558
Opened 2018-10-03 10:37 UTC by StlMaris123

Team akaringular final blog

2018-10-15 10:45 UTC, v-thakkar requested changes

2018-10-15 10:45 UTC, nerdyvaishali commented on blog/_posts/2018_10_02_akaringular_final_blog.md
> +permalink: blog/2018-09-05-team-akaringular
Hi @StlMaris123 ! Lovely blog post. Thanks for the PR. Just a minor comment here: Permalink and file name should be the same. So, please change them. 

I don't have any other comments for improving your blog post but if you wish to add some stats about your work, feel free to send revised commit. I plan to publish your post sometime at the end of this week so you can send revised commit until then. Thanks.

2018-10-15 11:21 UTC, StlMaris123 commented
Hi @nerdyvaishali , does that include the underscores?

2018-10-29 15:21 UTC, v-thakkar approved these changes

2018-10-29 15:22 UTC, nerdyvaishali commented
Hi @StlMaris123 ! Actually yes it does. But anyway, I'll fix that while merging the post. Thanks.

2018-10-31 11:14 UTC, merged