Mirrorconf blog potatocode
rails-girls-summer-of-code/summer-of-code pull request #573
Opened 2018-11-15 19:04 UTC by Sveijk

2018-11-15 19:11 UTC, Sveijk commented
Hi @nerdyvaishali 

Would you please check this PR if you have time? I managed to remove the old blogpost from 17 september, which has been published on 4th of October. Now that first blogpost is not in this PR anymore and the new blogpost is in it. Let me know if this is OK?

Kind regards, 
Sabine

2018-11-18 09:47 UTC, v-thakkar requested changes

2018-11-18 09:47 UTC, nerdyvaishali commented on blog/_posts/2018-10-04-Hurdles-of-a-beginning-developer.md
> -Overall, we had a great smooth time at Rails Girls, with very few hiccups along the way because we were lucky to have our amazing supervisors and mentors. Going forward, I think we'll find that havin
@Sveijk This file is still here. :) Please remove it.

2018-11-19 10:27 UTC, Sveijk commented
Hi @nerdyvaishali 

I think I fixed the issue now🙋‍♀️

2018-11-22 08:26 UTC, v-thakkar requested changes

2018-11-22 08:26 UTC, v-thakkar commented on blog/_posts/2018-11-03-potatoCode-at-MirrorConf.md
> +<iframe width="560" height="315" src="https://www.youtube.com/embed/uFBDLT7GmbA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
Hi @Sveijk ! This video fails to load. Can you please fix that?

2018-11-22 08:26 UTC, v-thakkar commented on blog/_posts/2018-11-03-potatoCode-at-MirrorConf.md
> +<img src="/img/blog/2018/2018-10-23-potatoCode-at-MirrorConf-AlinaSabineTalk.jpg" alt="Alina & Sabine talk, hurdles of a beginning dev">
Also, all images fails to load as well. Can you please use markdown style to embed images?

2018-11-24 07:37 UTC, Sveijk commented
Hi @nerdyvaishali !
Could you check if this will work? I fixed all images to be in Markdown and made links to youtube videos.

Best regards🙋‍♀️

2018-11-26 07:50 UTC, nerdyvaishali commented
@Sveijk Thanks, the blog post looks good now. I'll merge and publish the post today.

2018-11-26 07:51 UTC, v-thakkar approved these changes

2018-11-26 17:33 UTC, merged

2018-11-26 19:45 UTC, Sveijk commented
Thank you very much Vaishali!
It's been a long time coming so glad all worked out fine now 🙋‍♀️

Best regards
Sabine

Op ma 26 nov. 2018 om 08:50 schreef vaishali Thakkar <
notifications@github.com>:

> @Sveijk <https://github.com/Sveijk> Thanks, the blog post looks good now.
> I'll merge and publish the post today.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rails-girls-summer-of-code/summer-of-code/pull/573#issuecomment-441547244>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQvITCwEIcDu3P8LZfWV6GQ3I8D2k0_rks5uy51ZgaJpZM4Yhv74>
> .
>